# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ivan Daschinsky
title: Senior java software engineer
email: ivandasch@gmail.com
website: ivandasch.github.io/cv

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ivandasch
github_username:  ivandasch
linkedin_username: ivan-dashchinsky-1b15778a

about_profile_image: images/photo.jpeg
about_content: |
  Software engineer with more than 10 years experience.
  [Apache Ignite commiter](https://people.apache.org/keys/committer/ivandasch).


content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Apache Ignite
        icon: fab fa-github
        link: github.com/apache/ignite
        description: |
          Active member of community since 2018, have made many contributions, bug fixes etc.
          Notably:
          - [Apache Ignite python thin client](https://github.com/apache/ignite-python-thin-client).
            - Implemented asyncio version.
            - Fixed a lot of bug fixes, performance enhancements.
            - I am an active maintainer, released all of the recent versions by myself.
          - Platforms (Ignite.C++ and Ignite.NET)
            - Added ability to call .NET services from java nodes.
            - Introduced CMake build system for Ignite.C++ and replaced deprecated ones (Visual Studio projects and autotools).
            - Many bug fixes.
          - Took part in developing Apache Calcite based query engine.
          - Implemented NUMA aware memory allocator (C++ JNI module + Java).
          - Took part in developing integration testing framework based on [ducktape](https://github.com/confluentinc/ducktape).
            - Designed a python part and implemented a huge part of it.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Sbertech
        caption: Mar 2020 - Present
        link: https://sber-tech.com
        description: |
          - Developing Apache Ignite
          - Support and troubleshooting of Apache Ignite installations.
      - layout: left
        title: Reiffeisen Bank Russia
        link: https://dgtl.raiffeisen.ru
        caption: Jul 2019 - Mar 2020
        description: |
          - Developing core functionality of mobile bank's backend.
      - layout: left
        title: GridGain
        link: https://www.gridgain.com
        caption: Mar 2018 - Mar 2019
        description: |
          - Developing Apache Ignite and GridGain.
          - Customer support and troubleshooting.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Moscow State University, Physics Department
        sub_title: MSc Mathematical physics
        caption: 2002 - 2008

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
